language: node_js
node_js:
  - "8.10"
sudo: required
install:
- npm install
cache:
  directories:
  - node_modules
jobs:
  include:
  - stage: eslint
    name: Code quality check
    script: npm run eslint
  - stage: tests
    name: Test client-side code
    script: npm run test:client
  - stage: tests
    name: Test server-side code
    script: npm run test:server
  - stage: build
    name: Build web app
    script: npm run build  
  - stage: release
    script: echo Release....
    name: Docker push image
    if: tag IS present
    deploy:
      provider: script
      script: bash docker_push.sh
      skip_cleanup: true
      on:
        tags: true