language: node_js
sudo: required
node_js:
- '8'
before_install:
- yarn
cache:
  yarn: true
  directories:
  - node_modules
jobs:
  include:
  - stage: eslint
    name: Code quality check
    script: yarn eslint
  - stage: test-client
    name: Test client-side code
    script: yarn test:client
  - stage: test-server
    name: Test server-side code
    script: yarn test:server
deploy:
  provider: heroku
  api_key:
    secure: bb/G201RF4IpKojx2ibJL3sDxEzLFh0RT0swU0As4T/qzDeCf8dkw+n+UvQyTCbLzERxo7U+Zxql41wi+z0Qi5NQb2rGqaGzuTV1feEgBBGtIGCutDJKe+sO9sRpOzY9Kp+PWT4iKVL40fVlDCkx8V8lT8ZIFdF5gtQ3b450ceK6Gpbs7IyPbBj19npjTcHyidiBRQCExsi8a3oWaTogHf/SB/2UmleQhkOLFOLZ1baV2PSVJIZADmd/LiTLLJcH7h6BNfTYOtb6B5LwI7NFcaZveSGx632YK5X6IxMLU+3NOvICxhMSJJvxaR/L73o28iqFRE/rAcdZu4VcMSghpfKwVtTqd54eQaeF038MK5ectJT7zNfbbtW5SH8EQKCwytRoKI0733AAiuIZJxINfyrd3oF29wswFjA7S2sYyx3hYT38MY35CNHAs3Y0Gry0N8+5mkK953v5kKspzIjnB4FqxSNw8WA2RVSSiQG4r67eo6paOn4aKPnkNZJkfjx5xT6HxNNMXP+qIOwNwHhOOYrDLgj/UJOI9nsDdViPle4mqbOnjadDCCXoVygE0DeNgVxze4bGduBoB5l+GFF9zNLE69q1h9Toyd0jwsuRcPBn10bqX0BdfDicfks8HObkXjS1c4h0pphuACaldD1q3m6/0PVg+Q8loYj1bvqdJgY=
  app:
    develop: rewt-staging
    master: rewt-production
  on:
    repo: lukw34/react-express-webpack-template
