language: node_jsnode_js:- '8'

sudo: required

before_install:
- npm install
cache:
  directories:
  - node_modules
jobs:
  include:
  - stage: eslint
    name: Code quality check
    script: npm run eslint
  - stage: tests
    name: Test client-side code
    script: npm run test:client
  - stage: tests
    name: Test server-side code
    script: npm run test:server
  - stage: deploy
    name: Create docker image
    script: sh docker_push.sh
    if: tag = true