language: node_js
sudo: required
node_js:
- '8'
before_install:
- yarn
cache:
  yarn: true
  directories:
  - node_modules
jobs:
  include:
  - stage: eslint
    name: Code quality check
    script: yarn eslint
  - stage: test-client
    name: Test client-side code
    script: yarn test:client
  - stage: test-server
    name: Test server-side code
    script: yarn test:server
deploy:
  provider: heroku
  api_key:
    secure: Ekwzsu6VArnIFkY1VUzcdkwpvrMYStSjLU1tWuMJnJLBsJrVKQqaFT6eEgHr3KYMSf2ob3BLKSJ6BuXUMkImYNMIhxGY2NBxF1aEFQgdw+qr6EpaJSxA0rEasR9Gw0F3NQaW/V0mw6g0ChSu1wMvGKLppZ5Ng5G40q3vO6uimMt7BT8O1l34ogyn5urg6o9YpXjc7aDlQwUSsT1PJldtC2Y8O3WN4U6ZbvRn2biC9gmo/4y0Y0FctOeflPuJxFOBB3CskyieQDPhao7hwHNZvM7zwkf913F21Pm9bKrpl7TiMEQp1NsKfB1fTW0zCiSy+dPYGZ7TaWOOXF4NRw3t/nKYdotbkFlfLdqgg1BpaGzKdxQLtR/nRstULWxjQ9ix8/kWDqlX1YPJvfXSi9ynbS5kI3gJQ3duAwjR4QTs+EEhpoVHn0o1U/e6y+rGwtxJniDAzp6U64eM9/FBudQhoiLHbBlFJo65P31wfNhAq2yCOZEMEjYD5frg7j9QVDDx7abai97BU38Rq4jRSsYnUsymhwRPtugRzrACrhEFp1lMmQdf9PTZqT9PCIQaIq7xz63NRedSK9XPIv2sOUQ9wOCaYh/TlGTl793yIKGN/7+ljJaHyKV/hH6FGcoEcGhtwVJqmEXztt8fbq1FDr11U3+9O3IoHE4yjByUYvyLlDQ=
  app:
    develop: rewt-staging
    master: rewt-production
  on:
    repo: lukw34/react-express-webpack-template
